### ISSUE TITLE
sh: 1: /usr/local/lib/R/site-library/rTIMESAT/exec/TSF_process.exe: Exec format error

### ISSUE THREAD

**Issue by przell** [rpkgs/rTIMESAT#1]
Hi Dong Dong Kong, 
I am trying to use the rTIMESAT package on a linux system (docker). 
I tried to run your example code in `inst/example/rTIMESAT.r`. It fails when calling the last command `TSF_process(file_set)`.
The error i get is:
```
sh: 1: /usr/local/lib/R/site-library/rTIMESAT/exec/TSF_process.exe: Exec format error
```
Some more clarification:
- I have not put `TSF_process.exe` and `TSF_fit2time` on the system environment path. How can I do this on unbuntu? If this is necessary it would be great if you could add in the README.md how to do it for Ubuntu/Windows/Mac.
- I have not installed any additional timesat software since it is not mentioned as a dependency.

Thanks for this package! Really looking forward to getting it to work!
All the best, 
Peter

**Comment by przell** [comment]
Another add on:
Just figured out that .exe is only executable by windows. 
Could you provide a hint on how to use this on linux?

**Comment by kongdd** [comment]
Sorry. It works smoothly in my PC, wsl ubuntu 20.04.
